const movieData = [
  {
    adult: false,
    backdrop_path: "/jnE1GA7cGEfv5DJBoU2t4bZHaP4.jpg",
    genre_ids: [28, 878],
    id: 1094844,
    original_language: "en",
    original_title: "Ape vs. Mecha Ape",
    overview:
      "Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.",
    popularity: 1827.512,
    poster_path: "/dJaIw8OgACelojyV6YuVsOhtTLO.jpg",
    release_date: "2023-03-24",
    title: "Ape vs. Mecha Ape",
    video: false,
    vote_average: 5.527,
    vote_count: 55,
  },
  {
    adult: false,
    backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
    genre_ids: [28, 878, 12],
    id: 823464,
    original_language: "en",
    original_title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    popularity: 1909.929,
    poster_path: "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 6.531,
    vote_count: 878,
  },
  {
    adult: false,
    backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "en",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 1427.554,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.394,
    vote_count: 537,
  },
  {
    adult: false,
    backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    genre_ids: [878, 12],
    id: 693134,
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    popularity: 1523.958,
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.2,
    vote_count: 3545,
  },
  {
    adult: false,
    backdrop_path: "/3ffPx9jqg0yj9y1KWeagT7D20CB.jpg",
    genre_ids: [16, 28, 10751, 35, 14],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 1341.333,
    poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 7.148,
    vote_count: 1453,
  },
  {
    adult: false,
    backdrop_path: "/tpiqEVTLRz2Mq7eLq5DT8jSrp71.jpg",
    genre_ids: [878, 28, 18],
    id: 934632,
    original_language: "en",
    original_title: "Rebel Moon - Part Two: The Scargiver",
    overview:
      "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
    popularity: 1347.472,
    poster_path: "/cxevDYdeFkiixRShbObdwAHBZry.jpg",
    release_date: "2024-04-19",
    title: "Rebel Moon - Part Two: The Scargiver",
    video: false,
    vote_average: 6.1,
    vote_count: 614,
  },
  {
    adult: false,
    backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
    genre_ids: [27, 9648, 53],
    id: 1041613,
    original_language: "en",
    original_title: "Immaculate",
    overview:
      "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
    popularity: 965.876,
    poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
    release_date: "2024-03-20",
    title: "Immaculate",
    video: false,
    vote_average: 6.282,
    vote_count: 344,
  },
  {
    adult: false,
    backdrop_path: "/qGJASuD3fs9ZBxuEZoxCLVidVq8.jpg",
    genre_ids: [12, 28, 18],
    id: 845111,
    original_language: "fr",
    original_title: "Les trois mousquetaires : Milady",
    overview:
      "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
    popularity: 854.279,
    poster_path: "/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg",
    release_date: "2023-12-13",
    title: "The Three Musketeers: Milady",
    video: false,
    vote_average: 6.563,
    vote_count: 364,
  },
  {
    adult: false,
    backdrop_path: "/fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg",
    genre_ids: [28, 80, 53],
    id: 1105407,
    original_language: "en",
    original_title: "Damaged",
    overview:
      "A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.",
    popularity: 669.403,
    poster_path: "/eacWm6jPrjkpqhi4VzwqYeJWL6k.jpg",
    release_date: "2024-04-12",
    title: "Damaged",
    video: false,
    vote_average: 4.873,
    vote_count: 59,
  },
  {
    adult: false,
    backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
    genre_ids: [18, 12],
    id: 618588,
    original_language: "en",
    original_title: "Arthur the King",
    overview:
      "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
    popularity: 767.496,
    poster_path: "/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg",
    release_date: "2024-03-15",
    title: "Arthur the King",
    video: false,
    vote_average: 6.845,
    vote_count: 87,
  },
  {
    adult: false,
    backdrop_path: "/ilK1JRbMjo4sMJtNKLOKnqRf1RH.jpg",
    genre_ids: [10752, 28, 36],
    id: 976906,
    original_language: "en",
    original_title: "Spitfire Over Berlin",
    overview:
      "August 1944. With the American Eighth Air Force poised to strike over Nazi Germany, British Intelligence learns that they could be flying into a deadly trap. With only hours to spare, Flight Lieutenant Edward Barnes must fly a life and death mission over Berlin in his unarmed Spitfire to obtain photographic evidence and save the lives of 1200 men.",
    popularity: 718.794,
    poster_path: "/xtPPOPTad1qopK6uDe3VlYUa22o.jpg",
    release_date: "2022-05-13",
    title: "Spitfire Over Berlin",
    video: false,
    vote_average: 4.286,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    genre_ids: [28, 14],
    id: 634492,
    original_language: "en",
    original_title: "Madame Web",
    overview:
      "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    popularity: 718.301,
    poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    release_date: "2024-02-14",
    title: "Madame Web",
    video: false,
    vote_average: 5.617,
    vote_count: 1188,
  },
  {
    adult: false,
    backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 655.779,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.51,
    vote_count: 1262,
  },
  {
    adult: false,
    backdrop_path: "/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg",
    genre_ids: [878, 28, 14, 12],
    id: 601796,
    original_language: "ko",
    original_title: "외계+인 1부",
    overview:
      "Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.",
    popularity: 670.405,
    poster_path: "/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg",
    release_date: "2022-07-20",
    title: "Alienoid",
    video: false,
    vote_average: 6.781,
    vote_count: 301,
  },
  {
    adult: false,
    backdrop_path: "/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg",
    genre_ids: [28, 53],
    id: 359410,
    original_language: "en",
    original_title: "Road House",
    overview:
      "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
    popularity: 661.302,
    poster_path: "/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
    release_date: "2024-03-08",
    title: "Road House",
    video: false,
    vote_average: 7.018,
    vote_count: 1644,
  },
  {
    adult: false,
    backdrop_path: "/keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg",
    genre_ids: [28, 53, 10752],
    id: 784651,
    original_language: "hi",
    original_title: "फाइटर",
    overview:
      "Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.",
    popularity: 630.946,
    poster_path: "/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg",
    release_date: "2024-01-24",
    title: "Fighter",
    video: false,
    vote_average: 5.183,
    vote_count: 52,
  },
  {
    adult: false,
    backdrop_path: "/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg",
    genre_ids: [16, 878, 28],
    id: 1209288,
    original_language: "en",
    original_title: "Justice League: Crisis on Infinite Earths Part Two",
    overview:
      "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?",
    popularity: 625.273,
    poster_path: "/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg",
    release_date: "2024-04-22",
    title: "Justice League: Crisis on Infinite Earths Part Two",
    video: false,
    vote_average: 6.51,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
    genre_ids: [878, 12, 28],
    id: 653346,
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview:
      "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
    popularity: 667.893,
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    release_date: "2024-05-08",
    title: "Kingdom of the Planet of the Apes",
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg",
    genre_ids: [878, 9648, 53],
    id: 720321,
    original_language: "en",
    original_title: "Breathe",
    overview:
      "Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.",
    popularity: 549.236,
    poster_path: "/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg",
    release_date: "2024-04-04",
    title: "Breathe",
    video: false,
    vote_average: 4.975,
    vote_count: 61,
  },
  {
    adult: false,
    backdrop_path: "/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg",
    genre_ids: [80, 10749, 53],
    id: 948549,
    original_language: "en",
    original_title: "Love Lies Bleeding",
    overview:
      "Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.",
    popularity: 653.291,
    poster_path: "/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg",
    release_date: "2024-03-08",
    title: "Love Lies Bleeding",
    video: false,
    vote_average: 7.0,
    vote_count: 108,
  },
  {
    adult: false,
    backdrop_path: "/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg",
    genre_ids: [10752, 28, 18],
    id: 929590,
    original_language: "en",
    original_title: "Civil War",
    overview:
      "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
    popularity: 575.584,
    poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    release_date: "2024-04-10",
    title: "Civil War",
    video: false,
    vote_average: 7.401,
    vote_count: 545,
  },
  {
    adult: false,
    backdrop_path: "/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg",
    genre_ids: [28, 53],
    id: 984324,
    original_language: "fr",
    original_title: "Le salaire de la peur",
    overview:
      "When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.",
    popularity: 649.377,
    poster_path: "/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg",
    release_date: "2024-03-28",
    title: "The Wages of Fear",
    video: false,
    vote_average: 5.738,
    vote_count: 208,
  },
  {
    adult: false,
    backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 603.8,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.111,
    vote_count: 7847,
  },
  {
    adult: false,
    backdrop_path: "/bxmiZSQhQ581Y3vbEgpTtmEjt67.jpg",
    genre_ids: [18, 10749],
    id: 937287,
    original_language: "en",
    original_title: "Challengers",
    overview:
      'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
    popularity: 483.935,
    poster_path: "/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
    release_date: "2024-04-18",
    title: "Challengers",
    video: false,
    vote_average: 7.425,
    vote_count: 293,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 531.836,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.787,
    vote_count: 11472,
  },
  {
    adult: false,
    backdrop_path: "/rVJfabCz1ViynQCEz54MRqdZig1.jpg",
    genre_ids: [16, 878, 28],
    id: 1155089,
    original_language: "en",
    original_title: "Justice League: Crisis on Infinite Earths Part One",
    overview:
      "Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!",
    popularity: 469.865,
    poster_path: "/zR6C66EDklgTPLHRSmmMt5878MR.jpg",
    release_date: "2024-01-08",
    title: "Justice League: Crisis on Infinite Earths Part One",
    video: false,
    vote_average: 7.647,
    vote_count: 194,
  },
  {
    adult: false,
    backdrop_path: "/6a3aiSYNqABoV1Fq8n10LMOBxhH.jpg",
    genre_ids: [28, 53],
    id: 821937,
    original_language: "vi",
    original_title: "578: Phát Đạn Của Kẻ Điên",
    overview:
      "A container truck driver, Hùng, lives an idyllic life with his little daughter, An. The father and daughter become the closest companions in every journey with their orange container truck. Life goes on like that until An has to leave her father to go to school. One day, Hùng is informed that An is suffering from severe depression. Relying on his old skills in the past and finding out the truth, Hùng becomes enraged and painful to know that his little girl was kidnapped by a male stranger. Starting his lone and intense journey looking for and chasing after the unknown abuser, Hùng realizes that to hunt down that psychopath he has to counter the massive underground forces behind him.",
    popularity: 563.118,
    poster_path: "/8Nw5v7wPfa2FwbKyx61K2nIBcKa.jpg",
    release_date: "2022-05-20",
    title: "578: Magnum",
    video: false,
    vote_average: 5.158,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/dcnSWFCtk4b2aIzkhq6IDbzoIf1.jpg",
    genre_ids: [28, 35],
    id: 942047,
    original_language: "en",
    original_title: "Outsource",
    overview:
      "A police chief hires an old friend, who is an international spy, to help him search for a wanted suspect in the Philippines. When the chief dies, all evidence points towards the spy, and he must go to extremes to defend himself.",
    popularity: 438.074,
    poster_path: "/zIAF0UXtCJTJOYNYWiBfyifaaOi.jpg",
    release_date: "2022-01-18",
    title: "Outsource",
    video: false,
    vote_average: 2.3,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
    genre_ids: [27],
    id: 938614,
    original_language: "en",
    original_title: "Late Night with the Devil",
    overview:
      "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
    popularity: 467.492,
    poster_path: "/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
    release_date: "2024-03-19",
    title: "Late Night with the Devil",
    video: false,
    vote_average: 7.354,
    vote_count: 264,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 538.25,
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    video: false,
    vote_average: 7.125,
    vote_count: 5103,
  },
  {
    adult: false,
    backdrop_path: "/cIztAxDn3H8JylRaJwiHHpkGe53.jpg",
    genre_ids: [10751, 35, 16],
    id: 1239146,
    original_language: "en",
    original_title: "Woody Woodpecker Goes to Camp",
    overview:
      "After getting kicked out of the forest, Woody thinks he's found a forever home at Camp Woo Hoo — until an inspector threatens to shut down the camp.",
    popularity: 400.269,
    poster_path: "/mMnzNYvpqLLLdgF5TMmXfuy6wzx.jpg",
    release_date: "2024-04-12",
    title: "Woody Woodpecker Goes to Camp",
    video: false,
    vote_average: 6.801,
    vote_count: 108,
  },
  {
    adult: false,
    backdrop_path: "/kvJZLS607m1xVtEE8w95gmQ6MHE.jpg",
    genre_ids: [27],
    id: 1015303,
    original_language: "en",
    original_title: "Elevator Game",
    overview:
      "Follows socially awkward teenager Ryan, who discovers that the night his sister disappeared she had played ‘The Elevator Game’ — a ritual conducted in an elevator in which players attempt to travel to another dimension using a set of rules that can be found online. Ignoring warnings, he resolves to follow and find her.",
    popularity: 384.578,
    poster_path: "/a4Zb13jow8RqJkYFgCUSdmzJCWq.jpg",
    release_date: "2023-07-12",
    title: "Elevator Game",
    video: false,
    vote_average: 4.7,
    vote_count: 52,
  },
  {
    adult: false,
    backdrop_path: "/k0ucFBBgSDTXYU8fVHXJyjAuIIe.jpg",
    genre_ids: [27],
    id: 1063879,
    original_language: "fr",
    original_title: "Vermines",
    overview:
      "Residents of a rundown French apartment building battle against an army of deadly, rapidly reproducing spiders.",
    popularity: 692.586,
    poster_path: "/dY98PkUAbIGUUg0FhXEcOkbzHIZ.jpg",
    release_date: "2023-12-27",
    title: "Infested",
    video: false,
    vote_average: 7.2,
    vote_count: 141,
  },
  {
    adult: false,
    backdrop_path: "/9c0lHTXRqDBxeOToVzRu0GArSne.jpg",
    genre_ids: [878, 28],
    id: 935271,
    original_language: "en",
    original_title: "After the Pandemic",
    overview:
      "Set in a post-apocalyptic world where a global airborne pandemic has wiped out 90% of the Earth's population and only the young and immune have endured as scavengers. For Ellie and Quinn, the daily challenges to stay alive are compounded when they become hunted by the merciless Stalkers.",
    popularity: 404.935,
    poster_path: "/p1LbrdJ53dGfEhRopG71akfzOVu.jpg",
    release_date: "2022-03-01",
    title: "After the Pandemic",
    video: false,
    vote_average: 4.8,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: "/atPlFdUrQl2U9MtUwujrrjnQHBA.jpg",
    genre_ids: [28, 80, 18, 53],
    id: 654739,
    original_language: "ko",
    original_title: "발신제한",
    overview:
      "On his way to work, a bank manager receives an anonymous call claiming there's a bomb under his car seat, and if anyone exits the car, it will explode unless he can pay a ransom.",
    popularity: 482.61,
    poster_path: "/y2Aimt8isimtigec3e4kB2G9FMR.jpg",
    release_date: "2021-06-23",
    title: "Hard Hit",
    video: false,
    vote_average: 7.677,
    vote_count: 175,
  },
  {
    adult: false,
    backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
    genre_ids: [35, 12],
    id: 346698,
    original_language: "en",
    original_title: "Barbie",
    overview:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    popularity: 478.894,
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    release_date: "2023-07-19",
    title: "Barbie",
    video: false,
    vote_average: 7.07,
    vote_count: 8137,
  },
  {
    adult: false,
    backdrop_path: "/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg",
    genre_ids: [28, 14, 35],
    id: 43074,
    original_language: "en",
    original_title: "Ghostbusters",
    overview:
      "Following a ghost invasion of Manhattan, paranormal enthusiasts Erin Gilbert and Abby Yates, nuclear engineer Jillian Holtzmann, and subway worker Patty Tolan band together to stop the otherworldly threat.",
    popularity: 417.95,
    poster_path: "/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg",
    release_date: "2016-07-14",
    title: "Ghostbusters",
    video: false,
    vote_average: 5.4,
    vote_count: 6187,
  },
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 28, 12],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 386.678,
    poster_path: "/AgHbB9DCE9aE57zkHjSmseszh6e.jpg",
    release_date: "2024-03-07",
    title: "Damsel",
    video: false,
    vote_average: 7.135,
    vote_count: 1713,
  },
  {
    adult: false,
    backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
    genre_ids: [28, 12, 35],
    id: 293660,
    original_language: "en",
    original_title: "Deadpool",
    overview:
      "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
    popularity: 419.08,
    poster_path: "/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
    release_date: "2016-02-09",
    title: "Deadpool",
    video: false,
    vote_average: 7.612,
    vote_count: 29813,
  },
  {
    adult: false,
    backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    genre_ids: [80, 53, 18],
    id: 475557,
    original_language: "en",
    original_title: "Joker",
    overview:
      "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    popularity: 430.524,
    poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    release_date: "2019-10-01",
    title: "Joker",
    video: false,
    vote_average: 8.162,
    vote_count: 24505,
  },
];
module.exports = movieData;
